name: MLflow CI - Diabetes Model

on:
  push:
    branches: [ main ]
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MLflow and dependencies
        run: |
          pip install mlflow dagshub scikit-learn pandas joblib

      - name: Run MLflow Project (Train Model)
        run: |
          cd MLProject
          mlflow run . --experiment-name "Diabetes Prediction - CI"

      - name: Build Docker Image with MLflow
        run: |
          cd MLProject
          mlflow models build-docker -m ./mlruns/0/*/artifacts/model -n ${{ secrets.DOCKERHUB_USERNAME }}/diabetes_model:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_API_KEY }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes_model:latest
